### ISSUE TITLE
Version verification fails for ipfs daemon version 0.5.0

### ISSUE THREAD

**Issue by ingokeck** [ipfs-shipyard/py-ipfs-http-client#199]
Hi,
connecting to an ipfs daemon version 0.5.0 fails with the following error, even though the error message implies it should be supported:

> ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '[0, 5, 0]' (not in range: [0, 4, 3] – [0, 5, 0])

The problem seems to be the '>=' in line 65 of ipfshttpclient/client/__init__.py:

> 	if minimum > version or version >= maximum:
		raise exceptions.VersionMismatch(version, minimum, maximum)

I believe a ">" there makes more sense, as "maximum" implies to to be part of the intervall.

**Comment by AliabbasMerchant** [comment]
Maybe it was meant to be a python-like range(last value not considered)? 🤔 
@alexander255 ?

**Comment by ingokeck** [comment]
Could be (and makes kind of sense to not support the next big-version), but in this case would very confusing as it clashes with common conventions/definitions in mathematics regarding intervals and maxima/minima.

**Comment by alexander255** [comment]
@AliabbasMerchant: Yes, it is supposed to be a Python-like range. Do the new go-ipfs versioning scheme the new maximum version should now be `"1.0.0"`.

@ingokeck: True, but we generally only know the next *non-supported* version, rather then the last supported version (it not being released yet and everything). A better error message may be in order however:

> Unsupported daemon version '1.0.0' (not in range: 0.4.9 ≤ … < 1.0.0)

**Comment by alexander255** [comment]
I fixed the range reporting for 0.4.13. Current `master` also has support for go-IPFS 0.5 and hence doesn't error out on the version verification for that version anymore. Cheers!

**Comment by ingokeck** [comment]
Thanks!

**Comment by sohansoharab** [comment]
![image](https://user-images.githubusercontent.com/43113731/98509725-eacc7b00-228b-11eb-9dc7-a86530f1624d.png)
i dont know i'm getting the same problem again after updating ipfs, then I tried go-verion but still the same for me

**Comment by ntninja** [comment]
@sohansoharab: Try installing `ipfshttpclient==0.7.0a1`, instead of stable version to fix this.
